import { StyleSheet, Dimensions } from 'react-native';
import Styles from '../../config/styles';
const { width: viewportWidth , height: viewportHeight } = Dimensions.get('window');
const { color ,Typography} = Styles;

const MyOrdersStyles = StyleSheet.create({
    tabText:{
        textTransform:"capitalize",
        color:color.COLOR_WHITE,
        fontSize:Typography.fontSize,
        fontFamily:Typography.FONT_REGULAR,
        textAlign:'center', 
    },
    tabBox:{
        paddingHorizontal:viewportWidth*0.04,
        paddingVertical:viewportWidth*0.04,
        flex:1,
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:color.COLOR_PRIMARY,
    },
    border:{
        borderRightWidth:1,
        borderColor:color.COLOR_WHITE,
        opacity:.8,
        marginVertical:15
    },
    tabHeader:{
        display:'flex',
        flexDirection:'row',
        backgroundColor:color.COLOR_PRIMARY,
    },
    tabContent:{
        backgroundColor:color.COLOR_LIGHTGRAY,
        paddingVertical:viewportWidth*0.04,
        height:viewportHeight - 120,
    },
    tabContentSpace:{
        marginBottom:viewportWidth*0.1,
    },
    orderBox:{
        backgroundColor:color.COLOR_WHITE,
        marginHorizontal:viewportWidth*0.04,
        marginBottom:viewportWidth*0.04,
        padding:viewportWidth*0.04,
        borderRadius:viewportWidth*0.01
    },
    flexBox:{
        display:'flex',
        flexDirection:"row",
        justifyContent:'space-between',
        flexWrap:'wrap'
    },
    title:{
        color:color.COLOR_PRIMARY,
        fontSize:Typography.FONT_SIZE,
        fontFamily:Typography.FONT_REGULAR,
    },
    subtitle:{
        color:color.COLOR_DARKGRAY,
        fontSize:Typography.FONT_SIZE12,
        fontFamily:Typography.FONT_REGULAR,
        marginVertical:viewportWidth*0.01
    },
    locationText:{
        color:color.COLOR_PRIMARY,
        fontSize:Typography.FONT_SIZE14,
        fontFamily:Typography.FONT_REGULAR,
    },
    boldText:{
        fontFamily:Typography.FONT_MEDIUM
    },
    date:{
        color:color.COLOR_DARKGRAY,
        fontSize:Typography.FONT_SIZE12,
        fontFamily:Typography.FONT_MEDIUM
    },
    btnText:{
        color:color.COLOR_WHITE,
        fontSize:Typography.FONT_SIZE12,
        fontFamily:Typography.FONT_MEDIUM,
        backgroundColor:color.COLOR_PRIMARY,
        paddingVertical:viewportWidth*0.02,
        paddingHorizontal:viewportWidth*0.055,
        borderRadius:viewportWidth*0.013,
        justifyContent:'flex-end',
       display:'flex' 
    },
    buttonWidth:{
        position:'relative',
        height:45,
        width:'100%'
    },
    
    greenBtn:{
       position:'absolute',
       right:0
    },
    btnBottom:{
        alignItems:'center',
        marginTop:viewportWidth*0.02
    },
    green:{
        color:color.COLOR_PRIMARY,
        fontFamily:Typography.FONT_MEDIUM,
    },
    sortImg:{
        width:viewportWidth*0.035,
        height:viewportWidth*0.035,
        marginRight:viewportWidth*0.015
    },
    lineImg:{
        height:5
    },
    locationImg:{
        width:viewportWidth*0.035,
        height:viewportWidth*0.035,
        marginRight:viewportWidth*0.01
    },
    locationContent:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        flexWrap:'wrap',
        marginTop:viewportWidth*0.02
    }
});

export default MyOrdersStyles;
