//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

//AccountVerification
export const ACCOUNTVERIFICATION_REQUEST = 'ACCOUNTVERIFICATION_REQUEST';
export const ACCOUNTVERIFICATION_RESPONSE = 'ACCOUNTVERIFICATION_RESPONSE';
export const ACCOUNTVERIFICATION_FAILED = 'ACCOUNTVERIFICATION_FAILED';

//Forgot Password
export const FORGOTPASSWORD_REQUEST = 'FORGOTPASSWORD_REQUEST';
export const FORGOTPASSWORD_RESPONSE = 'FORGOTPASSWORD_RESPONSE';
export const FORGOTPASSWORD_FAILED = 'FORGOTPASSWORD_FAILED';

// Profile Image
export const LOADPROFILEIMAGE_REQUEST='LOADPROFILEIMAGE_REQUEST';
export const PROFILEIMAGELOADED_RESPONSE = 'PROFILEIMAGELOADED_RESPONSE';
export const FAILEDLOADINGPROFILEIMAGE_RESPONSE = 'FAILEDLOADINGPROFILEIMAGE_RESPONSE';